services:
  yikes:
    build: .
    ports:
      - "44317:4317"
  span-gen:
    build: ./span-gen
  otel-collector:
    image: "otel/opentelemetry-collector-contrib:0.113.0"
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
